# Generated by Django 5.2.7 on 2025-11-29 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_payment_licensekey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
    ]
