# Generated by Django 5.2.7 on 2025-11-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_remove_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_pid',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
