# Generated by Django 5.2.7 on 2025-11-30 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_stripe_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensekey',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_keys', to='checkout.orderitem'),
        ),
    ]
