# Generated by Django 5.2.7 on 2025-12-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_alter_licensekey_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='original_cart',
            field=models.TextField(blank=True, null=True),
        ),
    ]
