# Generated by Django 5.2.7 on 2025-11-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('base_game', 'Base Game'), ('currency', 'In-Game Currency')], max_length=20),
        ),
        migrations.DeleteModel(
            name='PhysicalProduct',
        ),
    ]
