# Generated by Django 5.2.7 on 2025-11-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='digitalproduct',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='digitalproduct',
            name='edition',
            field=models.CharField(blank=True, choices=[('standard', 'Standard Edition'), ('premium', 'Premium Edition'), ('ultimate', 'Ultimate Edition')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='digitalproduct',
            name='platform',
            field=models.CharField(blank=True, choices=[('pc', 'PC (Steam/Epic)'), ('xbox', 'Xbox'), ('nintendo', 'Nintendo Switch')], max_length=20, null=True),
        ),
    ]
