# Generated by Django 5.2.7 on 2025-11-28 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_digitalproduct_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('pc', 'PC (Steam/Epic)'), ('xbox', 'Xbox'), ('nintendo', 'Nintendo Switch')], max_length=20)),
                ('edition', models.CharField(choices=[('standard', 'Standard Edition'), ('premium', 'Premium Edition'), ('ultimate', 'Ultimate Edition')], max_length=20)),
                ('requires_key', models.BooleanField(default=True)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('sku', models.CharField(blank=True, max_length=64, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_variants', to='catalog.product')),
            ],
            options={
                'ordering': ['sort_order', 'platform', 'edition'],
                'unique_together': {('product', 'platform', 'edition')},
            },
        ),
    ]
