# Generated by Django 5.2.7 on 2025-11-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_digitalvariant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('base_game', 'Base Game'), ('digital', 'Digital Product'), ('currency', 'In-Game Currency')], max_length=20),
        ),
    ]
