# Generated by Django 5.2.7 on 2025-11-28 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_product_product_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='digitalvariant',
            options={'ordering': ['sort_order', 'platform', 'edition'], 'verbose_name': 'Base Game Variant', 'verbose_name_plural': 'Base Game Variants'},
        ),
    ]
