# Generated by Django 5.2.7 on 2025-11-28 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_digitalvariant_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'All Product', 'verbose_name_plural': 'All Products'},
        ),
    ]
