# Generated by Django 5.2.7 on 2025-11-28 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Product', 'verbose_name_plural': 'All Products'},
        ),
    ]
