# Generated by Django 5.2.7 on 2025-11-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalvariant',
            name='description',
            field=models.TextField(blank=True, help_text="Optional: Describe what's unique about this variant (e.g., 'Includes season pass, exclusive skins, early access')"),
        ),
    ]
