# Generated by Django 5.2.7 on 2025-11-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_digitalvariant_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalvariant',
            name='image',
            field=models.ImageField(blank=True, help_text='Edition specific image (uses product image if empty)', null=True, upload_to='variants/'),
        ),
        migrations.AlterField(
            model_name='digitalvariant',
            name='description',
            field=models.TextField(blank=True, help_text='Describe base game variants - edition/platform product details'),
        ),
    ]
