# Generated by Django 5.2.7 on 2025-11-29 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_digitalvariant_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyproduct',
            name='credit_amount',
            field=models.IntegerField(help_text='Number of in-game credits this purchase provides'),
        ),
        migrations.AlterField(
            model_name='currencyproduct',
            name='product',
            field=models.OneToOneField(help_text='Parent product this extends', on_delete=django.db.models.deletion.CASCADE, related_name='currency', to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='digitalproduct',
            name='edition',
            field=models.CharField(blank=True, choices=[('standard', 'Standard Edition'), ('premium', 'Premium Edition'), ('ultimate', 'Ultimate Edition')], help_text='Content edition level (optional)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='digitalproduct',
            name='platform',
            field=models.CharField(blank=True, choices=[('pc', 'PC (Steam/Epic)'), ('xbox', 'Xbox'), ('nintendo', 'Nintendo Switch')], help_text='Target platform (optional for multi-platform)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='digitalproduct',
            name='product',
            field=models.OneToOneField(help_text='Parent product this extends', on_delete=django.db.models.deletion.CASCADE, related_name='digital', to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='digitalproduct',
            name='requires_key',
            field=models.BooleanField(default=True, help_text='Whether this product needs a game key for activation'),
        ),
        migrations.AlterField(
            model_name='digitalvariant',
            name='description',
            field=models.TextField(blank=True, help_text="Edition-specific features (e.g., 'Includes season pass, exclusive skins')"),
        ),
        migrations.AlterField(
            model_name='digitalvariant',
            name='edition',
            field=models.CharField(choices=[('standard', 'Standard Edition'), ('premium', 'Premium Edition'), ('ultimate', 'Ultimate Edition')], help_text='Content edition level', max_length=20),
        ),
        migrations.AlterField(
            model_name='digitalvariant',
            name='image',
            field=models.ImageField(blank=True, help_text='Edition-specific image (falls back to product image if empty)', null=True, upload_to='variants/'),
        ),
        migrations.AlterField(
            model_name='digitalvariant',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this variant is available for purchase'),
        ),
        migrations.AlterField(
            model_name='digitalvariant',
            name='platform',
            field=models.CharField(choices=[('pc', 'PC (Steam/Epic)'), ('xbox', 'Xbox'), ('nintendo', 'Nintendo Switch')], help_text='Gaming platform for this variant', max_length=20),
        ),
        migrations.AlterField(
            model_name='digitalvariant',
            name='price_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional: Override base product price for this variant', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='digitalvariant',
            name='product',
            field=models.ForeignKey(help_text='Base game this variant belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='digital_variants', to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='digitalvariant',
            name='requires_key',
            field=models.BooleanField(default=True, help_text='Whether this variant needs a game key'),
        ),
        migrations.AlterField(
            model_name='digitalvariant',
            name='sku',
            field=models.CharField(blank=True, help_text='Unique identifier - auto-generated from base product SKU', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='digitalvariant',
            name='sort_order',
            field=models.IntegerField(default=0, help_text="Display order within the product's variants"),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(help_text='Main product description (shared across variants)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False, help_text='Highlight on homepage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Main product image (variants can have their own)', null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show in catalog'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Product display name', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Base price - variants can override this', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('base_game', 'Base Game'), ('digital', 'Digital Product'), ('currency', 'In-Game Currency')], help_text='Determines which extension model is used', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='Stock Keeping Unit - auto-generated if empty', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(help_text='URL-friendly identifier', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='Manual ordering within category'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When product was added to wishlist'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='product',
            field=models.ForeignKey(help_text='Product added to wishlist', on_delete=django.db.models.deletion.CASCADE, to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(help_text='User who wishlisted the product', on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to=settings.AUTH_USER_MODEL),
        ),
    ]
