# Generated by Django 5.2.7 on 2025-12-29 16:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_wishlist_unique_together_wishlist_variant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='wishlist',
            constraint=models.UniqueConstraint(fields=('user', 'product', 'variant'), name='uniq_wishlist_user_product_variant'),
        ),
        migrations.AddConstraint(
            model_name='wishlist',
            constraint=models.UniqueConstraint(condition=models.Q(('variant__isnull', True)), fields=('user', 'product'), name='uniq_wishlist_user_product_null_variant'),
        ),
    ]
